#!/bin/sh
# AI used: https://gemini.google.com/share/729c7bdd554e

case "$1" in
  start)
    echo "Loading LDD modules..."
    
    # i. Load scull (Customized from scull_load)
    # Assumes scull.ko is in /lib/modules/$(uname -r)/extra/ or similar
    modprobe scull || insmod /lib/modules/$(uname -r)/extra/scull.ko
    major=$(awk "\$2==\"scull\" {print \$1}" /proc/devices)
    rm -f /dev/scull[0-3]
    mknod /dev/scull0 c $major 0
    mknod /dev/scull1 c $major 1
    mknod /dev/scull2 c $major 2
    mknod /dev/scull3 c $major 3
    chmod 666 /dev/scull[0-3]

    # ii. Load faulty (Customized from module_load)
    modprobe faulty || insmod /lib/modules/$(uname -r)/extra/faulty.ko
    major_f=$(awk "\$2==\"faulty\" {print \$1}" /proc/devices)
    rm -f /dev/faulty
    mknod /dev/faulty c $major_f 0
    chmod 666 /dev/faulty

    # iii. Load hello
    modprobe hello
    ;;
    
  stop)
    echo "Unloading LDD modules..."
    
    # Unload hello
    rmmod hello
    
    # Unload faulty
    rmmod faulty
    rm -f /dev/faulty
    
    # Unload scull
    rmmod scull
    rm -f /dev/scull[0-3]
    ;;
    
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
esac

exit 0